
services:
  - type: web
    name: gutflow-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    rootDir: server
    envVars:
      - key: NODE_VERSION
        value: 18

  - type: web
    name: gutflow-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: client
